# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

target 'SwiftTextRecognition' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'TesseractOCRiOS', '4.0.0'
  # Pods for SwiftTextRecognition
  platform :ios, '11.0'

end
